{
    "plugins":[
        {
            "name":"小秋音乐",
            "url":"https://ghgo.xyz/raw.githubusercontent.com/sublime2025/MINE/refs/heads/master/MusicFree/Huibq/小秋音乐.js",
            "version":"0.3.0"
        },
        {
            "name":"小蜗音乐",
            "url":"https://ghgo.xyz/raw.githubusercontent.com/sublime2025/MINE/refs/heads/master/MusicFree/Huibq/小蜗音乐.js",
            "version":"0.3.0"
        },
        {
            "name":"小芸音乐",
            "url":"https://ghgo.xyz/raw.githubusercontent.com/sublime2025/MINE/refs/heads/master/MusicFree/Huibq/小芸音乐.js",
            "version":"0.3.0"
        },
        {
            "name":"小枸音乐",
            "url":"https://ghgo.xyz/raw.githubusercontent.com/sublime2025/MINE/refs/heads/master/MusicFree/Huibq/小枸音乐.js",
            "version":"0.3.0"
        },
        {
            "name":"小蜜音乐",
            "url":"https://ghgo.xyz/raw.githubusercontent.com/sublime2025/MINE/refs/heads/master/MusicFree/Huibq/小蜜音乐.js",
            "version":"0.3.0"
        },
        {
            "name":"酷狗",
            "url":"https://ghgo.xyz/raw.githubusercontent.com/sublime2025/MINE/refs/heads/master/MusicFree/猫头猫/酷狗.js",
            "version":"0.1.4"
        },
        {
            "name":"酷我",
            "url":"https://ghgo.xyz/raw.githubusercontent.com/sublime2025/MINE/refs/heads/master/MusicFree/猫头猫/酷我.js",
            "version":"0.1.6"
        },
        {
            "name":"网易",
            "url":"https://ghgo.xyz/raw.githubusercontent.com/sublime2025/MINE/refs/heads/master/MusicFree/猫头猫/网易.js",
            "version":"0.2.1"
        },
        {
            "name":"腾讯",
            "url":"https://ghgo.xyz/raw.githubusercontent.com/sublime2025/MINE/refs/heads/master/MusicFree/猫头猫/腾讯.js",
            "version":"0.2.1"
        },
        {
            "name":"bilibili",
            "url":"https://gitee.com/maotoumao/MusicFreePlugins/raw/master/dist/bilibili/index.js",
            "version":"0.2.2"
        }
    ]
}
